[package]
name = "penguin-kernel"
version = "0.0.0"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"

[[bin]]
name = "penguin-kernel"
path = "main.rs"

[dependencies]
penguin_utils = { path = "../utils", features = ["no_std"] }
spin = "0.7.1"
x86 = "0.36.0"
buddy_system_allocator = "0.7.0"
arrayvec = { version = "0.5.2", default-features = false, features = ["unstable-const-fn"] }
goblin = { version = "0.3", default-features = false, features = ["elf64"] }
bitflags = "1.2.1"
hashbrown = { version = "0.1.0", features = ["nightly"] }
