[package]
name = "penguin-kernel"
version = "0.0.0"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"

[[bin]]
name = "penguin-kernel"
path = "main.rs"

[dependencies]
spin = "0.7.1"
x86 = "0.36.0"
