[package]
name = "penguin_utils"
version = "0.0.0"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "penguin_utils"
path = "lib.rs"

[dependencies]
spin = "0.7.1"
