name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Docker
        run: docker ps

      - name: Set up Rust
        run: |
          rustup override set nightly
          rustup component add llvm-tools-preview rust-src clippy

      - name: Install cargo crates
        run: cargo install cargo-binutils rustfilt

      - name: Build Kerla
        run: make RELEASE=1

      - name: Lint
        run: make strict-lint

      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-system

      - name: Run unit tests
        run: make test RELEASE=1

      - name: Run integration tests
        run: >
          make run
          RELEASE=1
          INIT_SCRIPT="TESTS_DIR=/integration_tests /integration_tests/run.sh; halt -f"
          DISABLE_AUTO_CR_PRINT=1
          | tee run.log

      - name: Check if all integration tests are passed
        run: cat run.log | grep "Passed all integration tests"
